### ISSUE TITLE
Объединение проектов

### ISSUE THREAD

**Issue by proninyaroslav** [axet/android-torrent-client#31]
Здравствуйте. Меня зовут Ярослав и я надеюсь, что Вы не проигнорируете, увидев подобный заголовок, и дочитаете моё сообщение до конца :-) Я разрабатываю полностью свободный вариант торрент клиента для Android начиная с апреля (рзработка продвигалась достаточно медленно, так как нехватало времени). Ещё в марте я обнаружил, что несуществует полностью свободного торент клиента для Android. Максимум я нашёл только клиент для удалённого управления торрентами на ПК и некоторые мёртвые проекты свободных торрент клиентов (не считая frostwire, в нём много несвободных блобов и модулей сбора статистики). Тогда Вашего проекта на GitHub ещё не было, поэтому я решил писать программу с нуля, не опираясь на чьи-то наработки. На данным момент это полнофункциональный клиент, написание которого я надесю завершить до сентября (остались некоторые детали, в числе которых настройки, окно About и т.д. После завершения основной фазы разработки я собираюсь подготовить код для публикации на GitHub под лицензией GPL3. Я предлагаю Вам, после публикации кода моего проекта в свет, объеденить наши наработки и работать над усовершенствование единого, полностью свободного торрент клиента, не распыляясь на многочисленные проекты по всему Интернету. К тому же Ваш подход к видению клиента очень похож на мои наработки в данном деле. Я считаю, что любой вклад в Open Source базу на платформе Android в данный момент очень важен, но успеха на данном фронте мы не сможем добится, если не объеденим усилия над одним проектом, который в долгосрочной перспективе станет таким как, например, qBittorrent или Transmission на ПК платформах. Я понимаю, что Вы можете быть несколько удивлены моим предложением, но с момента начала разработки (апрель) я искал единомышленников на GitHub и буквально сегодня я увидел Ваш репозиторий и решил написать в надежде на то, что Вы откликнетесь на моё предложение.
Заранее благодарен за любой ответ.

**Comment by axet** [comment]
Я без лишних слов просто занимаюсь делом. Чего и вам желаю.

А так слова хорошие...
